# Generated by Django 2.2 on 2020-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_ownedcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedcar',
            name='date_of_purchase',
            field=models.DateField(default='yyyy-mm-dd'),
        ),
    ]
