# Generated by Django 2.2 on 2020-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200908_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedcar',
            name='car_model',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='date_of_last_service',
            field=models.DateField(blank=True, default='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='date_of_purchase',
            field=models.DateField(blank=True, default='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
