# Generated by Django 2.2 on 2020-09-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=140)),
                ('car_model', models.CharField(max_length=140)),
                ('vin', models.CharField(max_length=17)),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('date_of_last_service', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cars', to='clients.Client')),
            ],
        ),
    ]
