# Generated by Django 2.2 on 2020-09-08 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200908_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedcar',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='date_of_last_service',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ownedcar',
            name='date_of_purchase',
            field=models.DateField(blank=True),
        ),
    ]
